// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Toki.Interfaces
{
	public interface ISave : ISaveiOS
	{
		//if create return only exist recordType else return null
		//return key : recordName, value : jsonString if null no record
		string getJsonString();
#if UNITY_IOS
		
		//jsonStr - key : recordName, value : record data
		void setJsonString( string jsonStr );
#endif
	}
}