// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Toki.Interfaces
{
	public enum TwitterEvent
	{
		LOGIN_COMPLETE,
		LOGIN_FAIL,
		WRITE_COMPLETE,
		WRITE_CANCEL,
		WRITE_FAIL
	}
	
	public interface ITwitterBase : INative
	{
		bool isLoggedIn
		{
			get;
		}
		void initialize( string key, string secret );
		void login();
		void share( string message, string url );
	}
}